author: Woz
name: My Simple Dotenv
description: This action will read the .env file or parse a JSON secret and add variables to GITHUB_ENV.
branding:
  icon: box
  color: white
inputs:
  path:
    description: The path to the folder where the .env file is located.
    required: false
    default: './'
  mode:
    description: The mode for loading the .env file.
    required: false
    default: ''
  load-mode:
    description: Sets whether the program should fail when the .env file is not present (strict) or continue (skip).
    required: false
    default: 'strict'
  json-secret:
    description: A JSON string containing environment variables (as a GitHub Secret). If provided, this will be used instead of the .env file.
    required: false
    default: ''
runs:
  using: node20
  main: ./dist/index.js
